openapi: 3.0.0
info:
    title: Speco Api
    description: learning and implementing
    version: 1.0.0
    contact:
      email: jinalpansara@gmail.com
      name: Jinal Pansara
paths:
  /onboarding:
    get:
      description: Onboarding elements 
      responses:
       "200":
        description: 200 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Onboarding'
        
       "404":
        description: 404 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/errormodel'
        
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:408647264438:function:Speco_Api/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"      

  /PaymentPlans:
    get:
      description: PaymentPlans elements
      responses:
       "200":
        description: 200 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentPlans'
      
      
       "404":
        description: 404 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/errormodel'
              
      
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:408647264438:function:Speco_Api/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy" 
  
  /Doctor:
    post:
      description: Doctor elements
      responses:
       "200":
        description: 200 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Doctor'
      
      
       "404":
        description: 404 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/errormodel'
              
      
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:408647264438:function:Speco_Api/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy" 

  /Doctor/{DoctorId}:
    get:
      description: Doctor elements
      parameters:
        - name: DoctorId
          required: true
          in: path
          schema:
           type: integer
        
      responses:
       "200":
        description: 200 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Doctor'
      
      
       "404":
        description: 404 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/errormodel'
              
      
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:408647264438:function:Speco_Api/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy" 
        
  /Clinic:
    post:
      description: Clinic elements
      responses:
       "200":
        description: 200 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clinic'
      
      
       "404":
        description: 404 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/errormodel'
              
      
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:408647264438:function:Speco_Api/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy" 
        
    get:
      description: Clinic elements
      responses:
       "200":
        description: 200 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clinic'
      
      
       "404":
        description: 404 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/errormodel'
              
      
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:408647264438:function:Speco_Api/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy" 
    
  /Clinic/{ClinicId}:
    get:
      description: Clinic elements
      parameters:
        - name: ClinicId
          required: true
          in: path
          schema:
           type: integer
        
      responses:
       "200":
        description: 200 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clinic'
      
      
       "404":
        description: 404 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/errormodel'
              
      
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:408647264438:function:Speco_Api/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy" 
    
    put:
      description: Clinic elements
      parameters:
        - name: ClinicId
          required: true
          in: path
          schema:
           type: integer
      
        
      responses:
       "200":
        description: 200 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clinic'
      
      
       "404":
        description: 404 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/errormodel'
              
      
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:408647264438:function:Speco_Api/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy" 

    delete:
      description: Clinic elements
      parameters:
        - name: ClinicId
          required: true
          in: path
          schema:
           type: string
        
      responses:
       "200":
        description: 200 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clinic'
      
      
       "404":
        description: 404 response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/errormodel'
              
      
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:408647264438:function:Speco_Api/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy" 

  
components:
  schemas:
    Onboarding:
      type: array
      items: 
        type: object
        properties:
          Title: 
            type: string
          Description:
            type: string
          Image:
            type: string
            
    PaymentPlans:
      type: array
      items:
        type: object
        properties:
          Title:
            type: string
          Description: 
            type: string
          Image:
            type: string
          Button:
            type: string
    
    Doctor:
      type: array
      items:
        type: object
        properties:
          Name: 
            type: string
          RegistrationNo:
            type: string
          Practice:
            type: string
          Institute:
            type: string
          Experience:
            type: string
          Qualification:
            type: string
          Phone:
            type: string
          Procurement:
            type: string
          Overview:
            type: string
          Status:
            type: string
          Image:
            type: string
          OngoingPatient: 
            type: string
          TreatedPatient:
            type: string
          Id:
            type: string
          
          
    Clinic:
      type: array
      items: 
        type: object
        properties:
          ClinicName: 
            type: string
          RegistrationNo:
            type: string
          Location:
            type: string
          AadharCard:
            type: string
          EmailId:
            type: string
          QualificationName:
            type: string
          PhoneNumber:
            type: string
          InstituteName:
            type: string
          ClinicType:
            type: string
          ProcurementYear:
            type: string
          YearOfPractice:
            type: string
          AssociatedFacilities:
            type: string
          ClinicRegistration:
            type: string
          DoctorName:
            type: string
          Id:
            type: string
          
        
    errormodel:
      type: object
      required:
      - message
      - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
          
        
      
            
          
      
        
      
    
  
  
  